Notify user by email when job application state changes (#2010)
* ➕ Upgrade Sidekiq to 7.3.9

The previous version used to crash with the following error:

undefined method `broadcast' for class ActiveSupport::Logger

* Send email when job application state is updated

For a given list of states, each time the job application state changes, we send an email to the applicant to notify them and to remind them that they may have actions to do.

* Send email when job application is rejected

For a given list of rejection states, each time the job application state changes, we send an email to the applicant to notify them that the application has been rejected.

* ✅ Fix unprocessable entity

Rack status code name changes breaks HttpStatusMatcher:

https://github.com/rspec/rspec-rails/issues/2763

* Fix specs